### ISSUE TITLE
How can I download a whole tv series at once?

### ISSUE THREAD

**Issue by bnichs5** [ninthwalker/directPlexDownloader#1]
How can I download a whole tv series at once? And how do I get the metadata ID? Whenever I try to download, it saves a 3gb file to my downloads folder called bit321.tmp.

**Comment by ninthwalker** [comment]
Downloading a whole show isn't possible with this script. This in it's current state can only grab 1 show at a time or one movie. Whatever metadata ID you give to the script.

Not sure about a .tmp file. Probably because you didn't give the correct variables. Finding the metadata id and variables are found in the README.

**Comment by ninthwalker** [comment]
I’m looking into the .tmp issue though. Someone else had the issue as well so the backend Plex code may have changed so I may need to adjust the PS script for that.

**Comment by AleDema** [comment]
Any plan to make this work with whole shows?

**Comment by ninthwalker** [comment]
This script/repo is no longer maintained. Please see the new and improved plex downloader app called Saverr. This has a GUI and can do bulk downloads as well.
Thanks!
